---

all:
  hosts:
    node01:
      ansible_host: CHANGEME
    node02:
      ansible_host: CHANGEME
    node03:
      ansible_host: CHANGEME
  vars:
    ansible_connection_type: paramiko
    ansible_user: CHANGEME

primary:
  hosts:
    node01:
      ansible_host: CHANGEME
  vars:
    ansible_connection_type: paramiko
    ansible_user: CHANGEME
